### ISSUE TITLE
Add `create timestamp` for mongo db in table `azure_cosmosdb_mongo_database`

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-azure#154]
**Is your feature request related to a problem? Please describe.**
Add a column to store create time for mongo database.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
We are not getting the create timestamp details in API response.

**Comment by rajlearner17** [comment]
There is no external requirement for this. Marking this closed.
