### ISSUE TITLE
Add `create timestamp` column in table `azure_virtual_network_gateway` table

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-azure#179]
**Is your feature request related to a problem? Please describe.**
Use case:
`virtual network gateways that have been idle for more than 90 days. Because these gateways are billed hourly, you should consider reconfiguring or deleting them if you don't intend to use them anymore.`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
We are not getting the create time stamp details in response

**Comment by misraved** [comment]
Closing the issue since it is not on priority.
