### ISSUE TITLE
Add table azure_lb_nat_pool

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-azure#185]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by ParthaI** [comment]
Latest SDK version (github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-02-01/network) does not have a support to make api call for Load Balancer Nat Pool.

**Comment by rajlearner17** [comment]
We will reopen it based on requirements.
