### ISSUE TITLE
Table azure_key_vault is not listing the HSM managed vaults

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#224]
**Is your feature request related to a problem? Please describe.**
Table azure_key_vault is not listing vaults of type `Microsoft.KeyVault/managedHSMs`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
It will be a separate table `key_vault_managed_hardware_security_module` (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_hardware_security_module)

**Comment by ParthaI** [comment]
New issue has been created for adding new table so closing this issue. https://github.com/turbot/steampipe-plugin-azure/issues/233
