### ISSUE TITLE
Add virtualNetworkType column to the table azure_api_management

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#292]
**References**
https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-01-01-preview/api-management-service/list

Note: This detail is required for NIST SP 800 53 Rev 5 controls.

**Comment by c0d3r-arnab** [comment]
The `azure_api_management` table was already present. My PR will update the table based on the properties that we need
