### ISSUE TITLE
Need update in the query to change region from location.

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-azure#33]
In this link https://hub.steampipe.io/plugins/turbot/azure/tables/azure_storage_queue

The provides query may be replaced to region instead of location ?

select
name as queue_name,
storage_account_name,
location
from
azure_storage_queue;
Error: pq: column "location" does not exist

**Comment by debabrat-git** [comment]
![image](https://user-images.githubusercontent.com/43408569/109802020-452b8600-7c45-11eb-884b-79a511186616.png)
