### ISSUE TITLE
Add extension column azure_hybrid_kubernetes_connected_cluster

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azure#348]
**References**
New table or extension, based on the API support check.

This will provide strong support for Azure Arc management of Kubernetes clusters. 

This can help to address required extensions details from the Azure Arc-managed clusters. 

API can be referred 
https://docs.microsoft.com/en-us/rest/api/kubernetesconfiguration/extensions/list 

There is a request pending in hashicorp/terraform-provider-azurerm
https://github.com/hashicorp/terraform-provider-azurerm/issues/10635

**Comment by ParthaI** [comment]
There is no appropriate api call for getting the extension details, for future reference adding few links here
https://docs.microsoft.com/en-us/rest/api/kubernetesconfiguration/extensions/list
https://github.com/Azure/azure-sdk-for-go/blob/main/services/kubernetesconfiguration/mgmt/2021-03-01/kubernetesconfiguration/sourcecontrolconfigurations.go#L24
