### ISSUE TITLE
Add missing columns, diagnostic settings and fix existing columns in table_azure_app_service_environment.

### ISSUE THREAD

**Issue by c0d3r-arnab** [turbot/steampipe-plugin-azure#358]
Related link: https://docs.microsoft.com/en-us/rest/api/appservice/app-service-environments/list#code-try-0

- Add missing columns in table_azure_app_service_environment.
- Fix existing column like `dynamic_cache_enabled`.
- Add diagnostic settings.

**Comment by rajlearner17** [comment]
We will revisit fresh as required by the end-user
