### ISSUE TITLE
Add Security Center table

### ISSUE THREAD

**Issue by krishna5891** [turbot/steampipe-plugin-azure#36]
**Describe the new table**

Need to query the Security Center table to verify the CIS section 2 (Security Center)

**References**

Section 2

2.1 Ensure that Azure Defender is set to On for Servers (Manual)
2.2 Ensure that Azure Defender is set to On for App Service (Manual)
2.3 Ensure that Azure Defender is set to On for Azure SQL database servers (Manual)
2.4 Ensure that Azure Defender is set to On for SQL servers on machines (Manual)
2.5 Ensure that Azure Defender is set to On for Storage (Manual)
2.6 Ensure that Azure Defender is set to On for Kubernetes (Manual)
2.7 Ensure that Azure Defender is set to On for Container Registries (Manual)
2.8 Ensure that Azure Defender is set to On for Key Vault (Manual)
2.9 Ensure that Windows Defender ATP (WDATP) integration with Security Center is selected (Manual)
2.10 Ensure that Microsoft Cloud App Security (MCAS) integration with Security Center is selected (Manual)
2.11 Ensure that 'Automatic provisioning of monitoring agent' is set to 'On' (Automated)
2.12 Ensure any of the ASC Default policy setting is not set to "Disabled" (Manual)
2.13 Ensure 'Additional email addresses' is configured with a security contact email (Automated)
2.14 Ensure that 'Notify about alerts with the following severity' is set to 'High' (Automated)
2.15 Ensure that 'All users with the following roles' is set to 'Owner' (Automated)

**Comment by cbruno10** [comment]
@krishna5891 @bigdatasourav - Do we know what information from the security center we need per subscription and how that info lines up against the resources in the API (https://docs.microsoft.com/en-us/rest/api/securitycenter/)? I don't believe that having all security center resources/settings in a single table is a scalable design and over time, will grow quite large considering how many resources there are in security center.

Terraform also has separate resources (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/advanced_threat_protection), though not all that can be found in the API.

For a smaller, more scalable design, I believe we should look to add the tables required to check the benchmarks and break up the current, single table design we have in the open PR.

**Comment by bigdatasourav** [comment]
As discussed, separate tables will be created for security center.
