### ISSUE TITLE
Add PostgreSql server table

### ISSUE THREAD

**Issue by krishna5891** [turbot/steampipe-plugin-azure#37]
**Describe the new table**

Need to query the PostgreSql table to query and verify the CIS section 4.3 (PostgreSQL Database Server)

**References**

Section 4

We need to achieve some of the steps as per CIS recommendation
4.3.1 Ensure 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server (Automated)
4.3.2 Ensure 'Enforce SSL connection' is set to 'ENABLED' for MySQL Database Server (Automated)
4.3.3 Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.4 Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.5 Ensure server parameter 'log_disconnections' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.6 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.7 Ensure server parameter 'log_retention_days' is greater than 3 days for PostgreSQL Database Server (Automated)
4.3.8 Ensure 'Allow access to Azure services' for PostgreSQL Database Server is disabled (Manual)
4.4 Ensure that Azure Active Directory Admin is configured (Automated)
4.5 Ensure SQL server's TDE protector is encrypted with Customer-managed key (Automated)

**Comment by Subhajit97** [comment]
https://github.com/turbot/steampipe-plugin-azure/pull/64
This will unblock following CIS recommendations
```
Section 4

4.3.1 Ensure 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server (Automated)
4.3.3 Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.4 Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.5 Ensure server parameter 'log_disconnections' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.6 Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server (Automated)
4.3.7 Ensure server parameter 'log_retention_days' is greater than 3 days for PostgreSQL Database Server (Automated)
4.3.8 Ensure 'Allow access to Azure services' for PostgreSQL Database Server is disabled (Manual)
```

**Comment by Subhajit97** [comment]
https://github.com/turbot/steampipe-plugin-azure/pull/66
This will unblock following CIS recommendations
```
Section 4

4.3.2 Ensure 'Enforce SSL connection' is set to 'ENABLED' for MySQL Database Server (Automated)
```

**Comment by Subhajit97** [comment]
#67 
This will unblock following CIS recommendations
```
Section 4
4.4 Ensure that Azure Active Directory Admin is configured (Automated)
4.5 Ensure SQL server's TDE protector is encrypted with Customer-managed key (Automated)
```

Ensure that Azure Active Directory Admin is configured (Automated)
```sql
select
  name,
  id
from
  azure_sql_server
where
  server_azure_ad_administrator is not null;
```

Ensure SQL server's TDE protector is encrypted with Customer-managed key (Automated)
```sql
select
  name,
  encryp ->> 'kind' as encryption_kind,
  encryp -> 'properties' ->> 'serverKeyType' as encryption_key_type,
  encryp -> 'properties' ->> 'uri' as key_uri
from
  azure_sql_server,
  jsonb_array_elements(encryption_protector) as encryp
where
  encryp ->> 'kind' = 'azurekeyvault'
  and encryp -> 'properties' ->> 'serverKeyType' = 'AzureKeyVault'
  and encryp -> 'properties' ->> 'uri' is not null;
```
