### ISSUE TITLE
The `getAzureStorageAccountBlobProperties` hydrate call fails for some storage accounts in the `azure_storage_account` table

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-azure#405]
**Describe the bug**
Running `select * from azure_storage_account` for some storage accounts (unknown which types or configurations at the moment) will result in:
```
ERROR: rpc error: code = Unknown desc = Invoking Azure CLI failed with the following error: 
```

Other list/get/hydrate calls succeed in the same subscription.

Listing from the Azure CLI succeeds as well (`az storage blob service-properties show --account-name mystorageaccount`)

**Steampipe version (`steampipe -v`)**
v0.9.1

**Plugin version (`steampipe plugin list`)**
v0.20.0

**To reproduce**
Unknown at the moment

**Expected behavior**
Blob properties should be listed or be `nil` if not set on the storage accounts

**Additional context**

**Comment by misraved** [comment]
Fixed as a part of https://github.com/turbot/steampipe-plugin-azure/pull/418
