### ISSUE TITLE
 azure_ad_* tables are failing with error code `MissingSubscription`

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#407]
**Describe the bug**
 Below  tables are failing with  error code `MissingSubscription` 
 - azure_ad_user
 - azure_ad_group
 - azure_ad_service_principal

```
> select * from azure_ad_service_principal
Error: graphrbac.ServicePrincipalsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="MissingSubscription" Message="The request did not have a subscription or a valid tenant level resource provider."
> 

```
**Steampipe version (`steampipe -v`)**
 0.10.0-beta.2

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by cbruno10** [comment]
@khushboo9024 All of the Azure AD tables in this plugin have been re-implemented with a more recent SDK, in the [Azure AD plugin](https://hub.steampipe.io/plugins/turbot/azuread). We should switch all mods using the Azure AD tables in this plugin to instead use the related tables in the Azure AD plugin instead, and **not** fix the issues mentioned above as these tables have been deprecated as of v0.20.0.

**Comment by khushboo9024** [comment]
Closing this issue as these `azure_ad_* ` tables are deprecated and now we are switching all mods using the Azure AD tables in this plugin to instead use the related tables in the Azure AD plugin .
https://github.com/turbot/steampipe-mod-azure-compliance/pull/83
