### ISSUE TITLE
Include Environment in tables

### ISSUE THREAD

**Issue by jason1444** [turbot/steampipe-plugin-azure#416]
**Is your feature request related to a problem? Please describe.**
Currently in all Azure tables, we can't determine which environment the resources are in (AzureCloud, AzureUsgovernment, etc.) 

**Describe the solution you'd like**
I'd like to see environment added to all azure tables in the same way 'partition' exists in AWS tables to show the cloud environment.

**Comment by rajlearner17** [comment]
@jason1444 Thanks for raising the issue. Interesting suggestion. We will discuss this internally and respond back.
