### ISSUE TITLE
In the azure_compute_virtual_machine table show properties.virtualMachineScaleSet

### ISSUE THREAD

**Issue by jason1444** [turbot/steampipe-plugin-azure#417]
**Is your feature request related to a problem? Please describe.**
I'd like to have the VirtualMachineScaleSet property shown in the azure_compute_virtual_machine table. 
This property already exists within the get Virtual Machines API call.
https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/get#virtualmachine
![image](https://user-images.githubusercontent.com/89146579/144636457-f4bd7bcc-6c51-40c5-b448-e67ce1c79057.png)

**Describe the solution you'd like**
To have this property be available to query within the table.

**Comment by rajlearner17** [comment]
@jason1444 Thanks for using Steampipe!! 

Thank for the suggestion. We have already separate table [azure_compute_virtual_machine_scale_set](https://hub.steampipe.io/plugins/turbot/azure/tables/azure_compute_virtual_machine_scale_set), will this help for your use-case?
However, I am yet to check, if we can make a join and get the details associated with compute VM. But I agree if we have a direct way to get this property, will check and update with more details.

**Comment by jason1444** [comment]
Hi @rajlearner17, We'd like to be able to correlate the VM to a specific scale set which would be best done through the virtual_machines table

**Comment by rajlearner17** [comment]
@jason1444 Sorry for a delayed response on this,  we have experimented and found, there is no API response of `VirtualMachineScaleSet` in this [REST API call](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/get#virtualmachine) and for GO API it always comes as `null`

The Azure API remains different for VMs provisioned by `virtual machine` and  `scale sets `.

Hence we have already released new table [`azure_compute_virtual_machine_scale_set_vm`]
(https://hub.steampipe.io/plugins/turbot/azure/tables/azure_compute_virtual_machine_scale_set_vm)

**References**
[Azure Doc ](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview)
Azure [REST API for scale set VM](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list)
Go SDK - [scale set](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go)
Go SDK - [virtual machine ](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2017-12-01/compute/virtualmachines.go)

Let us know if this addresses your use case. Feel free to provide feedback.
