### ISSUE TITLE
OS Name and version in the azure_compute_virtual_machine table

### ISSUE THREAD

**Issue by jason1444** [turbot/steampipe-plugin-azure#419]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to get the OS Name and os Version from the azure_compute_virtual_machine table

**Describe the solution you'd like**
I'd like for these values to be in this table azure_compute_virtual_machine or create a new table from this API query https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/instance-view

**Describe alternatives you've considered**
I'd be open to other places to get the OS but as far as I can tell this information doesn't exist anywhere else

**Comment by rajlearner17** [comment]
@jason1444 Appreciate using steampipe and continuous feedback. Interesting to know that OS Name and OS Version are not captured. We are taking a look to find the reason, why we could not support it or it's part of any dataset.

**Comment by rajlearner17** [comment]
@jason1444 Current code does not have these columns added, sorry for the inconvenience. Good that we have found them to add, as we get these details from the `VirtualMachineInstanceView` function. We will work on it. Thanks for reporting it 👍 

[Reference](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/compute/mgmt/2020-06-01/compute#VirtualMachineInstanceView)
