### ISSUE TITLE
Add support to azure_app_service_web_app table to query security  features.

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-azure#42]
1. Authentication / Authorization.
2. TLS encryption
3. FTP deployments are disabled

**Comment by Paulami30** [comment]
We have this column `configuration` in the table where we have the `ftpsState`, `minTlsVersion` and `scmMinTlsVersion` properties. And we also have a column `auth_settings`.  Can you please mention if you are looking for any other information and also the CIS issues?

**Comment by cbruno10** [comment]
Closing issue as we have the columns @Paulami30 mentioned
