### ISSUE TITLE
Azure MySQL Server parameters request

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#427]
Azure SQL Server table "azure_mysql_server" does not have the following parameters to query:
- audit_log_enabled
- audit_log_events
- log_output
- slow_query_log
- log_slow_admin_statements

Is it possible to extend this from the Azure SDK that steampipe uses?

**Comment by rajlearner17** [comment]
@fgomesz Appreciate trying out Steampipe!! 

Based on your requirement, just trying to be more specific, are you interested to see some of these [MySQL Server Parameters](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-audit-logs-portal)? Correct me if wrong. 

Can you pls help us understand your use case? How you are planning to use Steampipe? This will help us to prioritize a few items mentioned in the case,  Azure SDK support for it.

**Comment by fgomesz** [comment]
Hello @rajlearner17 thank you!

Yes, it's those MySQL Server Parameters.

The use case is for security compliance checks:
- Audit_log_enabled   must be set to ON for all MySQL for Azure SQL instances
- Audit_log_events   must be set to include Connection and Admin on all MySQL for Azure SQL   instances
- Log_output   must be set to File on all MySQL for Azure SQL instances
- Slow_query_log   must be set to ON for all MySQL for Azure SQL instances
- Log_slow_admin_statements   must be set to ON for all MySQL for Azure SQL instances

thank you
