### ISSUE TITLE
Column remaining_retention_days value always comes as 0 in azure_storage_container table.

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-azure#435]
**Describe the bug**
Column remaining_retention_days value always comes as 0 in azure_storage_container table.

Below query fails - 
[reference](https://github.com/turbot/steampipe-plugin-azure/blob/main/docs/tables/azure_storage_container.md#list-containers-with-a-remaining-retention-period-of-7-days)
```
select
  name,
  id,
  type,
  account_name,
  remaining_retention_days
from
  azure_storage_container
where
  remaining_retention_days = 7;
```

**Comment by bigdatasourav** [comment]
Go SDK issue [reference](https://github.com/Azure/azure-sdk-for-go/issues/16751)

**Comment by rajlearner17** [comment]
@bigdatasourav pls check the response in Azure SDK https://github.com/Azure/azure-sdk-for-go/issues/16751
