### ISSUE TITLE
Implement query for Azure SQL AuditAction Groups property

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#445]
I'm trying to write compliance rules for Azure SQL AuditActionGroups (https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-action-groups-and-actions?view=sql-server-ver15#server-level-audit-action-groups).

I would like to be able to query the SQLAuditActionGroups property to know if it is set for example to "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP, FAILED_DATABASE_AUTHENTICATION_GROUP, and BATCH_COMPLETED_GROUP".

**Comment by rajlearner17** [comment]
@fgomesz Thank you for using Steampipe and submitting the issue, we are taking a look into this, will keep you posted.

**Comment by rajlearner17** [comment]
@fgomesz with the initial check I see, we have a property called `server_audit_policy` in `azure_sql_server`, here is the sample query, will this help? If now we will check further. 
```sql
select
  title,
  jsonb_pretty(ap -> 'properties' -> 'auditActionsAndGroups') as audit_actions_and_groups
from
  azure_sql_server s,
  jsonb_array_elements(server_audit_policy) as ap;
```

**Comment by rajlearner17** [comment]
@fgomesz Hi, just checking if this is good to close? Does the ^ query provide you with the data you were looking for?

**Comment by fgomesz** [comment]
Yes, it's perfect thank you
