### ISSUE TITLE
Fix column diagnostic_settings in azure_key_vault table.

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-azure#448]
**Describe the bug**
Column diagnostic_settings always returning null even if it has value for a key vault.

**Comment by ParthaI** [comment]
Not only the Azure SDK but also the azure-cli also have same issue, A support request has been raised for it.
Request Id: 2203170030000691

**Comment by ParthaI** [comment]
Not only the Azure SDK but also the azure-cli also have same issue, A support request has been raised for it.
Request Id: 2203170030000691

**Comment by ParthaI** [comment]
We got a response from Azure support team the api `https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/list#code-try-0` with version `2021-05-01-preview` returns the diagnostic settings details,  any other api version does not  seems to return any data for diagnostic settings details, We are currently on it.

**Comment by rajlearner17** [comment]
@ParthaI pls update the thread here https://github.com/Azure/azure-rest-api-specs/issues/18394
