### ISSUE TITLE
Fix table azure_storage_table list call throws OperationNotAllowedOnKind and FeatureNotSupportedForAccount error for unsupported storage account kind

### ISSUE THREAD

**Issue by as-bt** [turbot/steampipe-plugin-azure#457]
**Describe the bug**
Attempting to query the `azure_storage_table` table yields a connection error when one or more of the storage accounts are of type `BlobStorage`.

Error message:
```
Error: 1 connection failed:
connection 'CONNECTION_NAME': rpc error: code = Unknown desc = storage.TableClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="OperationNotAllowedOnKind" Message="The operation is not allowed on account kind BlobStorage" (SQLSTATE HV000)
```

It would appear that a [similar error](https://github.com/turbot/steampipe-plugin-azure/blob/main/azure/table_azure_storage_table.go#L98-L101) is already being handled for accounts of type `FileStorage`.

**Steampipe version**
v0.13.3

**Plugin version**
v0.24.0

**To reproduce**
Query `azure_storage_table` using a connection with a storage account type of `BlobStorage`.

**Expected behavior**
Steampipe should handle this exception to avoid a broken connection.

**Comment by ParthaI** [comment]
Thanks @as-bt For raising the issue and appreciate you interest towards steampipe, will definitely take a look into this issue.
