### ISSUE TITLE
Fix azure_storage_queue Queue is not supported for the storage account

### ISSUE THREAD

**Issue by as-bt** [turbot/steampipe-plugin-azure#458]
**Describe the bug**
Possibly related/similar to [issue 457](https://github.com/turbot/steampipe-plugin-azure/issues/457).

Attempting to query the `azure_storage_queue` table yields a connection error when one or more of the storage accounts are of an unsupported type. Azure does not provide the exact type which is unsupported, but the broken connection is the same one mentioned in issue 457 and breaks on account type `BlobStorage`.

Error:
```
Error: 1 connection failed:
connection 'CONNECTION_NAME': rpc error: code = Unknown desc = storage.QueueClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="Queue is not supported for the account." (SQLSTATE HV000)
```

It would appear that a [similar error](https://github.com/turbot/steampipe-plugin-azure/blob/main/azure/table_azure_storage_queue.go#L104-L107) is already being handled for accounts of type `FileStorage`.

**Steampipe version**
v0.13.3

**Plugin version**
v0.24.0

**To reproduce**
Query `azure_storage_queue` using a connection with a storage account type of `BlobStorage` (?).

**Expected behavior**
 Steampipe should handle this exception to avoid a broken connection.

**Comment by ParthaI** [comment]
@as-bt  thanks for bringing this up. We'll look into it.
