### ISSUE TITLE
Fix table azure_storage_account with AuthenticationFailed error for column blob_service_logging 

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-azure#466]
**Describe the bug**
If we have a storage account of type `Page Blobs` then column `blob_service_logging` fails to populate data, it is throwing `AuthenticationFailed` error as mentioned below.

```
Error: accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:8aa0fb2c-301c-0040-07f3-47bcc4000000\nTime:2022-04-04T07:15:56.2500595Z" (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
0.14.0-alpha.6

**Plugin version (`steampipe plugin list`)**
latest

**To reproduce**
- Create storage account of type `Page Blobs`
- Run the query `select name, blob_service_logging from azure_storage_account; ` or `select * from  azure_storage_account;`

**Expected behavior**
Instead of throwing error we should get the data

**Additional context**

**Comment by rajlearner17** [comment]
[Depends](https://github.com/turbot/steampipe-plugin-aws/issues/878)

**Comment by rajlearner17** [comment]
This addressed [here](https://github.com/turbot/steampipe-plugin-aws/issues/878)
https://github.com/turbot/steampipe-plugin-azure/blob/main/CHANGELOG.md#v0280-2022-06-09
