### ISSUE TITLE
Add table azure_security_center_automation

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#469]
It is not possible to query "Continuous Export" information from steampipe. Only information like "Export enabled" is implemented by the table "azure_security_center_setting" (https://hub.steampipe.io/plugins/turbot/azure/tables/azure_security_center_setting). 

However, I need information like "Security Alerts" level (High, Medium, Low, Informational) and Export target information like "Event Hub name" "Event Hub namespace" "Subscription"
https://docs.microsoft.com/en-us/azure/defender-for-cloud/continuous-export?tabs=azure-portal

I would like this information to be queried if possible:
- Continuous export (Event Hub)
- Exported data types > Security Alerts > level (High, Medium, Low, Informational)
- Export target > Event Hub (name, namespace, subscription)
just like in https://docs.microsoft.com/en-us/azure/defender-for-cloud/continuous-export?tabs=azure-portal

I haven't found any alternatives so far, besides doing it manually

Thank s in advance!

**Comment by ParthaI** [comment]
@fgomesz Thanks for using Steampipe!
Appreciate raising this issue here. We will definitely look into it.

**Comment by ParthaI** [comment]
@fgomesz We have added a new table (`azure_security_center_automation`) for the above-mentioned requirements. The changes are in the branch `issue-469`.

It would be great if you can try it out and your early feedback.
Some of the example queries are in [PR](https://github.com/turbot/steampipe-plugin-azure/pull/481)  

Steps to run the branch `issue-469`, in case it helps
- git clone https://github.com/turbot/steampipe-plugin-azure.git
- cd steampipe-plugin-azure
- git checkout issue-469
- steampipe service stop --force
- make
- steampipe query

**Comment by fgomesz** [comment]
Hi @ParthaI it looks good. Good job and thank you for the new table!

**Comment by cbruno10** [comment]
Hey @fgomesz , thanks for confirming the changes in the branch work for you!

I'm re-opening this issue for now, as the PR still isn't merged, but once it is, this issue will automatically close again.
