### ISSUE TITLE
Add Azure Active Directory table support.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azure#47]
This is to add most of the Azure IAM CIS requirements.

E.x.

- CIS v 1.3.0 : 1.22 Ensure Security Defaults is enabled on Azure Active Directory (Automated) : This is to check the Directory Properties whether enabled with defaults or not.
- Whether a maximum of 3 owners should be designated for subscription or not.

**Comment by debabrat-git** [comment]
1.1 Ensure that multi-factor authentication is enabled for all privileged users (Manual)
1.2 Ensure that multi-factor authentication is enabled for all non-privileged users (Manual)
1.4 Ensure that 'Allow users to remember multi-factor authentication on devices they trust' is 'Disabled' (Manual)
1.5 Ensure that 'Number of methods required to reset' is set to '2' (Manual)
1.6 Ensure that 'Number of days before users are asked to re-confirm their authentication information' is not set to "0" (Manual)
1.7 Ensure that 'Notify users on password resets?' is set to 'Yes' (Manual)
1.8 Ensure that 'Notify all admins when other admins reset their password?' is set to 'Yes' (Manual)
1.9 Ensure that 'Users can consent to apps accessing company data on their behalf' is set to 'No' (Manual)
1.10 Ensure that 'Users can add gallery apps to their Access Panel' is set to 'No' (Manual)
1.11 Ensure that 'Users can register applications' is set to 'No' (Manual)
1.12 Ensure that 'Guest user permissions are limited' is set to 'Yes' (Manual)
1.13 Ensure that 'Members can invite' is set to 'No' (Manual)
1.14 Ensure that 'Guests can invite' is set to 'No' (Manual)
1.15 Ensure that 'Restrict access to Azure AD administration portal' is set to 'Yes' (Manual)
1.16 Ensure that 'Restrict user ability to access groups features in the Access Pane' is set to 'No' (Manual)
1.17 Ensure that 'Users can create security groups in Azure Portals' is set to 'No' (Manual)
1.18 Ensure that 'Owners can manage group membership requests in the Access Panel' is set to 'No' (Manual)
1.19 Ensure that 'Users can create Microsoft 365 groups in Azure Portals' is set to 'No' (Manual)
1.20 Ensure that 'Require Multi-Factor Auth to join devices' is set to 'Yes' (Manual)

**Comment by rajlearner17** [comment]
This will be part of upcoming  azure-ad plugin
