### ISSUE TITLE
Add column ip_configurations in the table azure_subnet

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#472]
I really wanted to know which resources are hosted in specific subnets. 

It is possible to do so from the REST API, fetching "IPConfiguration" like on azure_compute_virtual_machine table ? (https://docs.microsoft.com/en-us/rest/api/virtualnetwork/subnets/list#ipconfiguration)

I've tried to do a join between azure_resource_group and virtual_network, but it will mix all the subnet resources.

**Comment by ParthaI** [comment]
@fgomesz Thanks for raising this issue. We will take a look into it.

**Comment by ParthaI** [comment]
Hi @fgomesz, we have a column named `ip_configurations` in table `azure_network_interface`, it shows the information about the IP configurations for a subnet. can you please cross-check and let us know if that helps you or not?

**Comment by fgomesz** [comment]
Hi @ParthaI, I'm afraid it does not help. I'm aware of that table and column, however it only shows which Virtual Machine resources are in a subnet. I need to know all of the resources. I've tried with other resources, for example a SQL server in a subnet does not have information to cross-check, not counting the other resources that can be on a subnet.

**Comment by ParthaI** [comment]
@fgomesz Sorry for the late reply, we have added an extra column (`ip_configurations`) in the `azure_subnet` table, which will help you get the IP configuration details for a subnet. The changes can be found in this [PR](https://github.com/turbot/steampipe-plugin-azure/pull/483) and the branch is  `issue-472`.

If you have the chance, please give it a try.
We appreciate your feedback on this.

Steps to run the branch `issue-472`

```
 git clone https://github.com/turbot/steampipe-plugin-azure.git
 cd steampipe-plugin-azure
 git checkout issue-472
 steampipe service stop --force
 make
 steampipe query
```

**Comment by fgomesz** [comment]
Hi @ParthaI it looks good. Good job and thank you for the new table!

**Comment by cbruno10** [comment]
Hey @fgomesz , thanks for confirming the changes in the branch work for you!

I'm re-opening this issue for now, as the PR still isn't merged, but once it is, this issue will automatically close again.
