### ISSUE TITLE
Fix azure_storage_share_file File is not supported for the storage account

### ISSUE THREAD

**Issue by as-bt** [turbot/steampipe-plugin-azure#474]
**Describe the bug**
Attempting to query the `azure_storage_share_file` table yields a connection error when one or more of the storage accounts do not support "File".

Error:
`connection 'CONNECTION_NAME': rpc error: code = Unknown desc = storage.FileSharesClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="File is not supported for the account." (SQLSTATE HV000)`

This error looks similar to previously submitted bug reports:
[458](https://github.com/turbot/steampipe-plugin-azure/issues/458)
[457](https://github.com/turbot/steampipe-plugin-azure/issues/457)

**Steampipe version**
0.13.6

**Plugin version**
0.25.0

**Comment by bigdatasourav** [comment]
@as-bt Thank you for providing input, this is inline with the other 2 issues you have mentioned. We will look into it.
