### ISSUE TITLE
Add Storage Account > logging enablement check for Blob, Table & Queue service.

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-azure#48]
Already there is logging support available for Storage Account, however enabling the logging in storage account level does not ensure the logging in Blob, Table & Queue service in it. 

Requirement is whether, logging is enabled  for read, write, and delete requests for above services. 

Ref: 
Azure CIS 1.3.0 > 3.3,3.10,3.11

**Comment by Subhajit97** [comment]
@rajmohanty17 
For CIS Section 3.3, we can try the following query
```
Section 3

3.3 Ensure Storage logging is enabled for Queue service for read, write, and delete requests (Manual)

select 
  name, 
  logging_delete, 
  logging_read, 
  logging_write, 
  logging_version, 
  logging_retention_days, 
  logging_retention_enabled 
from 
  azure_storage_account
where
  logging_read
  and logging_write
  and logging_delete;
```
