### ISSUE TITLE
Fix column access_control inconsistent state in table azure_logic_app_workflow 

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#484]
When the logic app is created, with "workflow settings" > "access control configuration" is initally set to "Any IP",

the following steampipe query returns null:
select access_control from azure_logic_app_workflow
+----------------+
| access_control |
+----------------+
| `<null>`         |
+----------------+

When I edit the settings to restrict with IP address (for example 123.123.123.123/32) the following steampipe query returns, which is fine:
select access_control from azure_logic_app_workflow
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| access_control                                                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"actions":{"allowedCallerIpAddresses":[{"addressRange":"123.123.123.123/32"}]},"triggers":{"allowedCallerIpAddresses":[{"addressRange":"123.123.123.123/32"}]}} |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+

When I revert the changes to allow "Any IP" again, steampipe returns an empty list:
select access_control from azure_logic_app_workflow
+----------------+
| access_control |
+----------------+
| {}             |
+----------------+

#### Suggestion
I suggest being consistent, either only using an empty list or just null when "access control configuration" is set to "Any IP".

This is not critical, but it can lead to inconsistent results when performing compliance queries for instance.

**Comment by ParthaI** [comment]
Thanks, @fgomesz for raising the issue, We will take a look.
