### ISSUE TITLE
Azure: Unable to see all subscriptions

### ISSUE THREAD

**Issue by ashitabh** [turbot/steampipe-plugin-azure#512]
I have 32 subscription for my azure AD login , however, streampipe is showing only 1 
Could you please help with this 
![image](https://user-images.githubusercontent.com/16971797/185287093-9f036470-155c-4fb4-8dbf-30e1ecd87ec4.png)

**Comment by cbruno10** [comment]
@ashitabh To expand on what @misraved has mentioned, in the Azure plugin, each connection represents a single subscription, as specified in the `Radius` section of [Azure Credentials](https://hub.steampipe.io/plugins/turbot/azure#credentials).

Here's a sample connection config with multiple Azure connections, one per subscription:

```hcl
connection "azure_all" {
  type        = "aggregator"
  plugin      = "azure"
  connections = ["azure_*"]
}

connection "azure_sub_1" {
  plugin          = "azure" 
  subscription_id = "azure_01"
}

connection "azure_sub_1" {
  plugin          = "azure"
  subscription_id = "azure_02"
}

connection "azure_sub_1" {
  plugin          = "azure" 
  subscription_id = "azure_03"
}
```

If you then run `select * id, subscription_id from azure_subscription`, you should see results from all 3 subscriptions, as the `azure_all` connection will be used as determine by the search path, but this can be changed by setting the [search path](https://steampipe.io/docs/guides/search-path#using-search_path-to-target-connections-and-aggregators). You can view your current search path by typing `.search_path`.

To query specific connections, you can also run queries like `select * id, subscription_id from azure_sub_1.azure_subscription` or `select * id, subscription_id from azure_sub_2.azure_subscription`. You can also use set the search path or search path prefix.

Hope that helps, if you have any other questions please let us know!

**Comment by KumarAshitabh** [comment]
thanks @cbruno10 
its working for multiple subscription
