### ISSUE TITLE
Add support to query App Service > Web App & Function App table  FTP & HTTP settings

### ISSUE THREAD

**Issue by rajmohanty17** [turbot/steampipe-plugin-azure#52]
This is to ensure FTP deployments are disabled for App Service. This will be available in App Service : [General Setting]

This will be helpful if we capture the Stack settings under general setting to validate the latest version of applications. 

Ref : Azure CIS 1.3.0 : 9.9, 9.10

![image](https://user-images.githubusercontent.com/26873346/110631743-dd3ce880-81cc-11eb-8be0-070badc2bad0.png)

**Comment by Subhajit97** [comment]
#77 

## 9.9 Ensure that 'HTTP Version' is the latest, if used to run the web app (Manual)

```sql
select
  name,
  enabled,
  region
from
  azure_app_service_web_app
where
  (configuration -> 'properties' ->> 'http20Enabled')::boolean;
```

## 9.10 Ensure FTP deployments are disabled (Automated)

```sql
select
  name,
  configuration -> 'properties' ->> 'ftpsState' as ftps_state
from
  azure_app_service_web_app
where
  configuration -> 'properties' ->> 'ftpsState' <> 'AllAllowed';
```
