### ISSUE TITLE
ExpiredAuthenticationToken errors when using Azure CLI credentials

### ISSUE THREAD

**Issue by JoshRosen** [turbot/steampipe-plugin-azure#521]
**Describe the bug**

When connecting to Azure with Azure CLI credentials, I eventually encounter errors like

```
Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '10/6/2022 7:35:55 PM' is earlier than current UTC time '10/6/2022 8:08:46 PM'."
```

after Steampipe has been running for a while. I haven't timed it exactly, but it feels like I'm running into this problem every 20-30 minutes.

It looks like automatic token refresh is not working: I have to run `steampipe service restart` to fix things.

It seems like this is a reoccurrence of an earlier bug: #261

**Steampipe version (`steampipe -v`)**

```
steampipe version 0.16.4
```

**Plugin version (`steampipe plugin list`)**

```
hub.steampipe.io/plugins/turbot/azure@latest     | 0.33.0 
hub.steampipe.io/plugins/turbot/steampipe@latest | 0.6.0
```

**Comment by misraved** [comment]
Sorry to hear that you are running into this issue @JoshRosen.

I tried to replicate this issue without much success. Could you please provide more details about the environment that you are running steampipe on? I found a conversation online, but I am not sure if it might help - https://github.com/Azure/azure-powershell/issues/6585

@LalitTurbot could you please provide some more insights on the fix that you made per  https://github.com/turbot/steampipe-plugin-azure/issues/261

**Comment by JoshRosen** [comment]
> I tried to replicate this issue without much success. Could you please provide more details about the environment that you are running steampipe on?

I'm running Steampipe on Mac OS 12.5.1 

`az --version` reports:

```
azure-cli                         2.40.0 *

core                              2.40.0 *
telemetry                          1.0.8

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

I'm using `az login --tenant <tenant-id>` to obtain Azure credentiasls.

My Azure configuration file looks like this (except there's several connections being aggregated):

```hcl
connection "azure_all" {
  type        = "aggregator"
  plugin      = "azure"
  connections = ["azure_*"]
}

connection "azure_test" {
  plugin  = "azure"
  subscription_id = "<subscription id>"
}
```

**Comment by misraved** [comment]
Hey @JoshRosen, apologies for the delay. @LalitTurbot has raised a fix for the issue - https://github.com/turbot/steampipe-plugin-azure/pull/544

Could you please give it a try from your end and check if it fixes your issue?

Thanks a lot for your patience 👍 and promptness in providing insightful details for us to replicate this issue 😄.

**Comment by JoshRosen** [comment]
@misraved, @LalitTurbot, https://github.com/turbot/steampipe-plugin-azure/pull/544 appears to have completely resolved my issue: I've been using it for a few hours and haven't hit any expired credential issues. Thanks for the fix!
