### ISSUE TITLE
Add Cost Information for Subscription

### ISSUE THREAD

**Issue by dgsauve** [turbot/steampipe-plugin-azure#522]
**I cannot query cost information about my azure subscriptions**
Azure's cost portal is not the most flexible, and I would like to be able to query subscription costs.

**Solution**
I would like to query azure subscription costs, possibly being broken down by resource group.

**Describe alternatives you've considered**
The alternative is to use steampipe to query resourcegroup to get cost center tags, then assemble data from steampipe and azure portal in excel. 

**Additional context**
I have been tasked with querying costs by resource group and tag by month, steampipe is much more flexible than azure portal, I'd love to see this functionality implemented.

**Comment by misraved** [comment]
Welcome to Steampipe @dgsauve 👍 and thanks for raising this request.

If anyone would like to attempt to develop this table, the APIs mentioned in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v67.0.0+incompatible/services/costmanagement/mgmt/2020-06-01/costmanagement/costmanagementapi#pkg-functions is an excellent place to start.
Additional links - https://learn.microsoft.com/en-us/rest/api/cost-management/

Please let us know in case there are questions 👍 .

**Comment by ledoyen** [comment]
not stale

**Comment by bigdatasourav** [comment]
@dgsauve, my apologies for the lack of communication regarding this issue.

We have identified an [API](https://learn.microsoft.com/en-us/rest/api/cost-management/query/usage?tabs=HTTP) that fulfils your requirements. We are actively investigating and conducting thorough testing of this API using various test cases. You can find all the relevant details and progress updates [here](https://github.com/turbot/steampipe-plugin-azure/blob/cost-mng/azure/table_azure_cost_management.go). We welcome your feedback and suggestions as we continue working on this. Rest assured; we will keep you informed of any further developments in this matter.

Here is a sample test output which fetches the cost per resource group of a particular subscription - 
```
> select 
  display_name as subscription,
  jsonb_pretty(columns) as columns,
  jsonb_pretty(rows) as rows
from 
azure_cost_management as m,
azure_subscription as s
where
m.subscription_id = s.subscription_id
+-----------------+----------------------------------+-------------------------------------------+
| subscription    | columns                          | rows                                      |
+-----------------+----------------------------------+-------------------------------------------+
| newwarriors AAA | [                                | [                                         |
|                 |     {                            |     [                                     |
|                 |         "name": "PreTaxCost",    |         0.001344086021505,                |
|                 |         "type": "Number"         |         20230611,                         |
|                 |     },                           |         "demo",                           |
|                 |     {                            |         "USD"                             |
|                 |         "name": "UsageDate",     |     ],                                    |
|                 |         "type": "Number"         |     [                                     |
|                 |     },                           |         0.000003,                         |
|                 |     {                            |         20230611,                         |
|                 |         "name": "ResourceGroup", |         "kp-test-k8-compliance_group",    |
|                 |         "type": "String"         |         "USD"                             |
|                 |     },                           |     ],                                    |
|                 |     {                            |     [                                     |
|                 |         "name": "Currency",      |         0.0000319298,                     |
|                 |         "type": "String"         |         20230611,                         |
|                 |     }                            |         "nist-test_group",                |
|                 | ]                                |         "USD"                             |
|                 |                                  |     ],                                    |
|                 |                                  |     [                                     |
|                 |                                  |         2.001683513643921,                |
|                 |                                  |         20230611,                         |
|                 |                                  |         "turbottest11815",                |
|                 |                                  |         "USD"                             |
|                 |                                  |     ],                                    |
|                 |                                  |     [                                     |
|                 |                                  |         0.000006,                         |
|                 |                                  |         20230611,                         |
|                 |                                  |         "turbottest28408",                |
|                 |                                  |         "USD"                             |
|                 |                                  |     ],                                    |
|                 |                                  |     [                                     |
|                 |                                  |         0.004267008,                      |
|                 |                                  |         20230611,                         |
|                 |                                  |         "turbottest37303",                |
|                 |                                  |         "USD"                             |
|                 |                                  |     ],                                    |
```

**Comment by bigdatasourav** [comment]
@dgsauve @ledoyen @John-Donalson, we have temporarily postponed the work above due to our current focus on higher-priority tasks. However, we plan to return to it shortly. In the meantime, if you would like, you are more than welcome to use the provided code as a starting point and make any necessary changes. We would appreciate it if you could raise a pull request (PR) with your changes. Feel free to also reach out to us if you need any help with the same.

**Comment by cbruno10** [comment]
As per the message above, we're closing this issue as not planned for now, but will re-open once we have time to revisit it (if another user wants to take up the work, please re-open).
