### ISSUE TITLE
Virtual Machine SKU table returning empty results for the capabilities tables

### ISSUE THREAD

**Issue by AnykeyNL** [turbot/steampipe-plugin-azure#523]
the virtual machine sku table should return the capabilities in the sku title, but is just showing an empty array.
https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list?tabs=HTTP#lists-all-available-resource-skus-for-the-specified-region

[https://files.slack.com/files-pri/T01SW2PU554-F047GG6CC94/screenshot_2022-10-22_141029.png](url)

**Comment by misraved** [comment]
Hey @AnykeyNL, sorry to see that you are running into issues.

I am unable to load the image link that you mentioned above. Could you please share a snapshot of the image?

Additionally, could you also share the query that returns an empty array (the exact column name would be really helpful)?

I tried searching for the column name mentioned in https://hub.steampipe.io/plugins/turbot/azure/tables/azure_mssql_virtual_machine#inspect but without any success!!

**Comment by AnykeyNL** [comment]
hi,

is it not the virtual machine table bit this one:

https://hub.steampipe.io/plugins/turbot/azure/tables/azure_compute_resource_sku

here you should be able to lookup based in the "size" variable in the virtual machine table what the actual capabilites of the VM are, lize cores, memory etc.

but it is here where the capabilities field is not being populated with data.

**Comment by misraved** [comment]
Thanks a lot @AnykeyNL for the information!! Let me take a look at it 👍 .

**Comment by AnykeyNL** [comment]
Just to give you the actual query vs az cli command:

Steampipe: select name,capabilities from azure_compute_resource_sku where name='Standard_B1s'
AZ CLI: az vm list-skus --size Standard_B1s

You will see steampipe does return the right amount of variables in the capabilities field, but the actual values are empty

**Comment by AnykeyNL** [comment]
Looking closer at is, I see all the fields that should contain a json array is returning empty field

**Comment by cbruno10** [comment]
Hey @AnykeyNL , by "all the fields", do you mean fields inside of the `capabilities` column in the `azure_compute_resource_sku` table, or are you referring to other columns/tables? If so, can you please provide more details? Thanks!

**Comment by AnykeyNL** [comment]
Here a screenshot example. Left showing output from steampipe, just an empty array, while the az cli command shows the actual values. Both run from the same environment with the same credentials.

[screenshot](https://i.postimg.cc/PrVmmfWf/steampipe-azure-issue.png)

**Comment by AnykeyNL** [comment]
So @cbruno10 the fields inside the capabilities is an empty json array.

**Comment by misraved** [comment]
Thanks once again @AnykeyNL for reporting this bug. The fix will be available in `v0.34.0` plugin version 👍 .

**Comment by misraved** [comment]
Hello @AnykeyNL, sorry to see that you are still running into issues. It's curious to see that you are still getting an empty JSON array. I personally tried to run the query now and I am able to see the results.

For instance - 

```
> select name,capabilities from azure_compute_resource_sku where name = 'Classic'
+---------+----------------------------------------------------------+
| name    | capabilities                                             |
+---------+----------------------------------------------------------+
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] |
| Classic | [{"name":"MaximumPlatformFaultDomainCount","value":"3"}] 
```

**Comment by AnykeyNL** [comment]
Doing the same  query (use credentials that have full admin rights)

>  select name,capabilities from azure_compute_resource_sku where name = 'Classic'
+---------+--------------+
| name    | capabilities |
+---------+--------------+
| Classic | [{}]         |
| Classic | [{}]         |
| Classic | [{}]         |
| Classic | [{}]         |

any idea how to best troubleshoot this?

**Comment by cbruno10** [comment]
@AnykeyNL If you're able to locally build the plugin by cloning the repo and using `make`, one suggestion is to add a new column to the `azure_compute_resource_sku` table:
```
{
	Name:        "raw",
	Description: "Raw data.",
	Type:        proto.ColumnType_JSON,
	Transform:   transform.FromValue(),
},
```

This will return all data each row is getting in full from the SDK, so you can run something like `select name, capabilities, jsonb_pretty(raw) as raw from azure_compute_resource_sku`.

If this works, can you please share the results from the `raw` column here so we can better understand what the SDK is giving back to you?

Thanks!

**Comment by AnykeyNL** [comment]
I was testing on an Ubuntu VM, and there I still have this issue. I just installed steampipe on my new Macbook and problem is NOT happening. 

So there must be a difference in the libraries or something, but I guess it is not the error of the Azure plugin. Will try to do more research
