### ISSUE TITLE
Fix column backend_ip_configuration for table azure_lb_nat_rule

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#534]
**Describe the bug**
Getting null value for column backend_ip_configuration for table azure_lb_nat_rule even if we have data.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by ParthaI** [comment]
We are getting only the id of the IP config in this column, but in SDK, we can see there are other properties available in the struct. [Azure rest API](https://learn.microsoft.com/en-us/rest/api/load-balancer/inbound-nat-rules/list?tabs=HTTP#code-try-0) returns the same result as Go SDK.

**Comment by ParthaI** [comment]
Closing this issue as no changes required from plugin side.
