### ISSUE TITLE
Add table azure_dns_zone

### ISSUE THREAD

**Issue by Shr3ps** [turbot/steampipe-plugin-azure#564]
**References**
- Terraform resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_zone
- Azure SDK Go: https://github.com/Azure/azure-sdk-for-go/tree/v68.0.0/services/dns/mgmt/2018-05-01/dns
- Models/attributes: https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/dns/mgmt/2018-05-01/dns/models.go#L597

**Comment by pdecat** [comment]
Hi @madhushreeray30, I've seen you've been assigned this issue. Did you start development of this table? Otherwise, I can give it a go.

**Comment by madhushreeray30** [comment]
Hello @pdecat, I haven’t started working on the table yet.
It would be great if you can take this up. Thank you so much for offering to contribute :thumbsup:. Looking forward to seeing this table on the hub :smiley:.

**Comment by pdecat** [comment]
Hi,

I've submitted https://github.com/turbot/steampipe-plugin-azure/pull/575 to implement this new table.

Now on to extensive testing...
