### ISSUE TITLE
Enhancing App Service table to provide the configuration details.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-azure#57]
One of the CIs requirement (9.11 Ensure Azure Keyvaults are used to store secrets (Manual)) need to ensure that App service App or Functions application using Azure Key Vault. 

We may need to capture few information from this https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references in  JSON Template for App Service Configuration.

**Comment by Subhajit97** [comment]
The API cause the following error:
```
Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity'
```

Raised with azure team
https://github.com/Azure/azure-sdk-for-go/issues/14509

**Comment by rajlearner17** [comment]
The SDK thread is updated to get the status - https://github.com/Azure/azure-sdk-for-go/issues/14509.

**Comment by rajlearner17** [comment]
We will check back later based on the user's requirement
