### ISSUE TITLE
Add table azure_kubernetes_service_version

### ISSUE THREAD

**Issue by misterjoshua** [turbot/steampipe-plugin-azure#606]
I'd like to list the available Azure Kubernetes Versions that are available in the region.

**References**
https://learn.microsoft.com/en-us/rest/api/aks/container-services/list-orchestrators?tabs=HTTP

**Comment by misraved** [comment]
Welcome to Steampipe @misterjoshua and thanks for raising a new table request 👍.

**Comment by misterjoshua** [comment]
I'd still like this feature

**Comment by ParthaI** [comment]
The [API](https://learn.microsoft.com/en-us/rest/api/aks/container-services/list-orchestrators?tabs=HTTP) has been deprecated and removed in the newer SDK version, There was a discussion going on in [Azure Go SDK repo](https://github.com/Azure/azure-sdk-for-go/issues/19007) to add this back, however it has not been added yet.
