### ISSUE TITLE
intrusion_detection_mode returning always null in azure_firewall_policy table

### ISSUE THREAD

**Issue by josuelaika** [turbot/steampipe-plugin-azure#608]
**Describe the bug**
I'm using the `azure_firewall_policy` table to basically list the firewall policies that have a `intrusion_detection_mode` configured, however, even tho I have a couple of firewalls configured with that setting, the value for that column is always null 

![image](https://user-images.githubusercontent.com/119522137/235974417-ca0acb05-c8bf-4fce-a4f6-37e48da2994b.png)

This is the query:
SELECT 
  name, 
  resource_group, 
  region as location, 
  intrusion_detection_mode, 
  CASE WHEN intrusion_detection_mode = 'FirewallPolicyIntrusionDetectionStateTypeAlert' THEN 'IDS' WHEN intrusion_detection_mode = 'FirewallPolicyIntrusionDetectionStateTypeDeny' THEN 'IPS' END as mode_type 
FROM 
  azure_firewall_policy

**Steampipe version (`steampipe -v`)**
v0.19.0

**Plugin version (`steampipe plugin list`)**
v0.41

**To reproduce**
run the query

**Expected behavior**
`intrusion_detection_mode` should return the value assigned instead of null

**Additional context**

**Comment by misraved** [comment]
@josuelaika thanks for catching this bug 👍.

The fix is now available in the `v0.41.1` plugin version 😃.
