### ISSUE TITLE
Add `backupItems` in table azure_recovery_services_vault

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#624]
**Is your feature request related to a problem? Please describe.**
Add `backupItems` in table azure_recovery_services_vault, this is required for Azure HIPAA HITRUST 9.2 compliance . 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<img width="1440" alt="image" src="https://github.com/turbot/steampipe-plugin-azure/assets/46913995/47db3fd1-b4ac-4cbe-9661-775b17898346">

**Comment by ParthaI** [comment]
In the current/latest version SDK we have client support the backups, but the API is not supported yet.

```
func NewBackupsClientWithBaseURI(baseURI string, subscriptionID string) BackupsClient {
	return original.NewBackupsClientWithBaseURI(baseURI, subscriptionID)
}
```

We will revisit the issue once the API support is available in the [SDK](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/profiles/latest/recoveryservices/mgmt/backup).
