### ISSUE TITLE
Add private endpoint connections columns in table azure_machine_learning_workspace

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#627]
**Is your feature request related to a problem? Please describe.**
Add private endpoint connections details in table azure_machine_learning_workspace

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/preview/machinelearningservices/mgmt/2020-02-18-preview/machinelearningservices#PrivateEndpointConnectionsClient.Get

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
@khushboo9024, I have identified some key findings related to this issue. Kindly review them below.

- The Azure plugin is currently using GO SDK version `v58.0.0+incompatible`.
- In this version, there is only a [Get API call](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/preview/machinelearningservices/mgmt/2020-02-18-preview/machinelearningservices#PrivateEndpointConnectionsClient.Get) available for retrieving Private Endpoint Connections.
- The Get API call requires three parameters: `resourceGroupName`, `workspaceName`, and `privateEndpointConnectionName`.
- We can obtain the `resourceGroupName` and `workspaceName` from our other hydrate calls, but we do not have access to the `privateEndpointConnectionName` for making this API call.
- I also checked the latest version of the GO SDK ([v68.0.0+incompatible](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/preview/machinelearningservices/mgmt/2020-02-18-preview/machinelearningservices?tab=versions)), but it does not yet support the List API call.
- However, I found in the Azure documentation that the [List API](https://learn.microsoft.com/en-us/rest/api/azureml/2023-06-01-preview/private-endpoint-connections/list?tabs=HTTP#code-try-0) is available.

Please review these findings and let me know your thoughts. Thanks!

**Comment by misraved** [comment]
@ParthaI thanks for adding in your observations 👍.

We will reopen this issue once the API support is available in the SDK 👍.
