### ISSUE TITLE
Query to azure_key_vault_secret crashes when keyvault name is camel-case

### ISSUE THREAD

**Issue by KingBrewer** [turbot/steampipe-plugin-azure#637]
**Describe the bug**
When a keyvault name contains capital letters the hydrate function crashes whilst querying the `azure_key_vault_secret` table

**Steampipe version (`steampipe -v`)**
0.20.9

**Plugin version (`steampipe plugin list`)**
- turbot/azure 0.46.0
- turbot/azuread 0.12.0

**To reproduce**
1. Create an Azure keyvault with **CamelCase** name
2. Create a secret in the keyvault
3. Run steampipe and list all secrets from azure_key_vault_secret table:
   ```sql
      > SELECT * FROM azure_key_vault_secret;
      Error: rpc error: code = Internal desc = hydrate function getTurbotData failed with panic runtime error: index out of range [4] with length 1 (SQLSTATE HV000)
   ```

**Expected behavior**
Correct list of secrets should be returned without errors for all key vaults, including those with name containing camel-case characters

**Additional context**
The issue appears to be caused specifically where the vault's name is being matched in [`getTurbotData()`](https://github.com/turbot/steampipe-plugin-azure/blob/v0.46.0/azure/table_azure_key_vault_secret.go#L250-L291) function: https://github.com/turbot/steampipe-plugin-azure/blob/v0.46.0/azure/table_azure_key_vault_secret.go#L273-L281.
The problem is that `vaultName` is derived from secret's ID, which is a lower case URI, and it doesn't match the name from the list of keyvaults, that may contain uppercase characters.

**Comment by ParthaI** [comment]
@KingBrewer, I'm sorry to hear that you've encountered an issue, and thank you for bringing it to our attention 👍

To address the problem, we have created a [Pull Request](https://github.com/turbot/steampipe-plugin-azure/pull/638). Hopefully, this PR will resolve the bug.

We would greatly appreciate it if you could test the changes and provide us with your feedback.

Here are the steps to test the PR:

1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-azure.git`
2. Navigate to the `steampipe-plugin-azure` directory: `cd steampipe-plugin-azure`
3. Switch to the `issue-637` branch: `git checkout issue-637`
4. Run the command `make` to build the changes.
5. Run the query.

Regarding listing the secrets by vault name using the WHERE clause (`select * from azure_key_vault_secret where vault_name = 'test-vault';`), please ensure that the vault name is in lowercase, even if it appears in camel case in the portal. The Vault Name is extracted from the Vault Secret ID, and the List/Get secret API always returns the Vault name in lowercase, regardless of the casing in the portal.

If you have any concerns or queries, please feel free to let us know. Thank you for your cooperation!
