### ISSUE TITLE
Add `Authentication type` column in table azure_app_configuration

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#643]
**Is your feature request related to a problem? Please describe.**
Add `Authentication type` column in table azure_app_configuration

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

<img width="1437" alt="image" src="https://github.com/turbot/steampipe-plugin-azure/assets/46913995/cdacbf56-d228-4fb1-b518-5c44f435e52f">

**Comment by misraved** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/21404
