### ISSUE TITLE
Add table azure_resource_health_emerging_issue

### ISSUE THREAD

**Issue by Lachlan-White** [turbot/steampipe-plugin-azure#664]
**References**
Get API:
https://github.com/Azure/azure-sdk-for-go/blob/v58.0.0/services/resourcehealth/mgmt/2017-07-01/resourcehealth/emergingissues.go#L34

List API:
https://github.com/Azure/azure-sdk-for-go/blob/v58.0.0/services/resourcehealth/mgmt/2017-07-01/resourcehealth/emergingissues.go#L105

**Comment by ParthaI** [comment]
Hello @Lachlan-White, I apologize for the delayed response.

We have created a preliminary pull request (PR) addressing this issue. Would you be willing to test it by switching to [this branch](https://github.com/turbot/steampipe-plugin-azure/pull/683) (`issue-664`)?

To test the branch, follow these steps:

1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-azure.git`
2. Navigate to the cloned directory: `cd steampipe-plugin-azure`
3. Execute the `make` command
4. Run your Steampipe query

Your feedback would be greatly appreciated. Please let us know if the results meet your expectations or if you require any further assistance.

Thank you!

**Comment by ParthaI** [comment]
Hi @Lachlan-White , Did you get a chance to give it a try?

**Comment by ParthaI** [comment]
Hello @Lachlan-White, have you had the opportunity to try it out yet?

**Comment by bigdatasourav** [comment]
Closing this issue for now, we will revisit this once we have an update from the SDK [issue](https://github.com/Azure/azure-sdk-for-go/issues/22272).

**Comment by misraved** [comment]
@ParthaI @bigdatasourav @Lachlan-White closing this issue at the moment, since the scope of [Azure SDK issue](https://github.com/Azure/azure-sdk-for-go/issues/22272) resolution involves a significant update to the Azure plugin's credential management code.

We will revisit this issue once an SDK update is made at a larger scale, including addressing breaking changes 👍.
