### ISSUE TITLE
Add table `azure_backup_policy` + items

### ISSUE THREAD

**Issue by Shr3ps** [turbot/steampipe-plugin-azure#723]
**References**
I found this in SDK: https://github.com/Azure/azure-sdk-for-go/blob/v58.0.0/services/recoveryservices/mgmt/2021-01-01/backup/models.go
And the associated Terraform data resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/backup_policy_vm

We would like to be able to query all backup policies available in Azure: vm backup, file share, containers, etc. and also be able to list all backup items attached to policies (vm item list attached to a backup VM policy, etc.)

I don't know if it's best to have a dedicated table for items or have a `jsonb` attribute in the policy table.

**Comment by ParthaI** [comment]
Hello, @Shr3ps, thanks for highlighting the issue.

Upon reviewing, I found that we are utilizing Azure GO SDK version `v58.0.0+incompatible`, which unfortunately lacks API support for listing all Backup policies in Azure Recovery Service. Could you specify which details you require from this [model](https://github.com/Azure/azure-sdk-for-go/blob/v58.0.0/services/recoveryservices/mgmt/2021-01-01/backup/models.go)? This will help us to design the table to meet our needs effectively.

Thank you!

**Comment by Shr3ps** [comment]
Hi @ParthaI 

I think would be great to have these struct equivalent in Steampipe:
```
type AzureFileShareProtectableItem struct {
AzureFileshareProtectedItem 

AzureIaaSClassicComputeVMProtectedItem 
AzureIaaSComputeVMProtectedItem

```

so we can have items attached to a recovery vault (and we can wait a bit later for Policies)

**Comment by ParthaI** [comment]
Thank you, @Shr3ps, for the information. I'll attempt it again and inform you if I encounter any further blockers.

**Comment by bigdatasourav** [comment]
Sample block which can be useful -

```
"github.com/Azure/azure-sdk-for-go/services/recoveryservices/mgmt/2021-01-01/backup"

ParentHydrate = listRecoveryServicesVaults

backupPoliciesClient := backup.NewPoliciesClientWithBaseURI(session.ResourceManagerEndpoint, subscriptionID)
backupPoliciesClient.List(ctx,vaultName,resourceGroupName,"")
```
