### ISSUE TITLE
Add `key rotation policy` information in table `azure_key_vault_key`

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-azure#733]
**Is your feature request related to a problem? Please describe.**

Add `key rotation policy` information in table `azure_key_vault_key`

https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/keyvault/mgmt/2022-07-01/keyvault/models.go#L890
https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/keyvault/mgmt/2022-07-01/keyvault/models.go#L3120

**Comment by ParthaI** [comment]
Hello @Priyanka-Chatterjee-2000, this plugin relies on Azure GO SDK [Version 58.0.0+incompatible](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/keyvault/mgmt/2019-09-01/keyvault#KeyProperties) for fetching KeyVault details. Unfortunately, this version does not include support for rotation policy details.

Additionally, upon reviewing other [versions](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/profiles/latest/keyvault) of the KeyVault packages, I found that they also do not provide Rotation Policy details.

The Rotation Policy details become available with the most recent version of the Azure Go SDK. We intend to address this issue after upgrading our Azure Go SDK package to the latest version.

Thank you for your patience!
