### ISSUE TITLE
Warning: executeQueries: query 1 of 1 failed: ERROR: relation "azuread_user" does not exist (SQLSTATE 42P01)

### ISSUE THREAD

**Issue by MathCarv** [turbot/steampipe-plugin-azure#752]
**Describe the bug**
Hello, I'm trying to run a query in steampipe from azure users but it's giving an error, I changed the one from before to azure_ad_user because it was out of use, but this one isn't working either. can anybody help me?

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.4

**Plugin version (`steampipe plugin list`)**
Installed: hub.steampipe.io/plugins/turbot/azure@latest
Version: 0.56.0
Connections: Azure

**To reproduce**
![image](https://github.com/turbot/steampipe-plugin-azure/assets/96321313/7ae28a90-47d9-48b8-89bf-b267d918a7da)

**Comment by cbruno10** [comment]
Hi @MathCarv , the `azuread_user` table is in the [Azure AD](https://hub.steampipe.io/plugins/turbot/azuread) plugin, so if you install that plugin and setup the connection (can use the same creds in the configuration), then you can query the `azuread_user` table.

**Comment by MathCarv** [comment]
Hi @cbruno10, I installed azuread, updated it to make sure, but the error still persists, what could it be?
![image](https://github.com/turbot/steampipe-plugin-azure/assets/96321313/e24938fe-96f6-4a30-8e65-1dfe1525ba31)

**Comment by MathCarv** [comment]
Here worked, the error was in the .scp file, thank you!
