### ISSUE TITLE
Add table azure_defender_cloud

### ISSUE THREAD

**Issue by marcbrlcln** [turbot/steampipe-plugin-azure#761]
**Description**
I can't find an existing table that allows me to query the service Microsoft Defender for Cloud for a given subscription. My use case is to verify that Microsoft Defender is configured in a subscription.

**Comment by ParthaI** [comment]
Hi @marcbrlcln, I was looking at this issue but discovered that there are no direct APIs available for the Microsoft Defender for Cloud service. Here's what we can do:

- To determine if Azure Defender (part of Microsoft Defender for Cloud, formerly known as Azure Security Center) is activated for a specific Azure subscription, you can use the Security Center Pricing API. 
- This will indicate whether Azure Defender is enabled ('Standard') or not ('Free') for Virtual Machines. Modify the query as needed for other services.
- We have several existing tables (such as `azure_security_center_automation`, `azure_security_center_contact`, `azure_security_center_jit_network_access_policy`, `azure_security_center_setting`, `azure_security_center_sub_assessment`, and `azure_security_center_subscription_pricing`) that can help confirm whether Microsoft Defender is configured in a subscription.
- Specifically, the `pricing_tier` column in the `azure_security_center_subscription_pricing` table will provide the necessary statistics.

Please let us know if this information is helpful to you.

Thanks!

**Comment by marcbrlcln** [comment]
Hi ! Thanks for these informations. Yes it was helpful.
