### ISSUE TITLE
Azure Standard Front Door resource details not listed in Steampipe Azure plugin

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-azure#764]
**Description**:
I am experiencing an issue with the Steampipe Azure plugin where Azure Front Door resources are not being listed as expected. Despite having created an Azure Front Door resource, the azure_frontdoor table returns an empty result set.

**Steps to Reproduce**:

Create an Azure Front Door resource using the Azure CLI or Azure Portal.
Verify the creation of the resource using az afd profile list:
```sh
az afd profile list
[
  {
    "extendedProperties": {},
    "frontDoorId": "b.............................................",
    "id": "/subscriptions/d46d..................................../resourcegroups/demo/providers/Microsoft.Cdn/profiles/test-123",
    "kind": "frontdoor",
    "location": "Global",
    "name": "test-123",
    "originResponseTimeoutSeconds": 60,
    "provisioningState": "Succeeded",
    "resourceGroup": "demo",
    "resourceState": "Active",
    "sku": {
      "name": "Standard_AzureFrontDoor"
    },
    "tags": {},
    "type": "Microsoft.Cdn/profiles"
  }
]
```

Attempt to list the Azure Front Door resources using Steampipe:
```sql
select * from azure_frontdoor;
```
**Expected Behavior**:
The Azure Front Door resource should be listed in the query result.

**Actual Behavior**:
The query returns an empty result set.

**Additional Information**:

- Azure CLI output confirms the existence of the Azure Front Door resource.
- The issue may be similar to [Azure CLI extension issue #5170](https://github.com/Azure/azure-cli-extensions/issues/5170), where `az network front-door list` returns an empty result.

**Comment by ParthaI** [comment]
Hi @Priyanka-Chatterjee-2000, The table `azure_frontdoor` is returning the data as expected.

```
> select * from azure_frontdoor;
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------------------+-----------------------------+---------------+------------>
| name            | id                                                                                                                                        | provisioning_state | type                         | cname                       | enabled_state | friendly_na>
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------------------+-----------------------------+---------------+------------>
| turbottest76782 | /subscriptions/************************************/resourcegroups/turbottest76782/providers/Microsoft.Network/frontdoors/turbottest76782 | Succeeded          | Microsoft.Network/frontdoors | turbottest76782.azurefd.net | Enabled       |            >
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------------------+-----------------------------+---------------+------------>

```

The command `az afd profile list` stands for the resource `Front Door and CDN profiles`. Currently, the table returns the data for `Azure CDN Standard from Microsoft (classic)` Not the `standard` one.

<img width="590" alt="Screenshot 2024-06-03 at 10 22 48 PM" src="https://github.com/turbot/steampipe-plugin-azure/assets/47887552/e61fe255-8436-4bc9-a480-627d658d8f04">

Please update the issue as per your requirements. 

Thanks!

**Comment by Priyanka-Chatterjee-2000** [comment]
@ParthaI need the details of the standard frontdoor but in table azure_frontdoor we get only classic ones details. Shall we have a new table to query standard frontdoor information?

**Comment by ParthaI** [comment]
@Priyanka-Chatterjee-2000, I believe this will be a separate table.
Terraform treats this it as a separate resource:
- [azurerm_frontdoor](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor)
- [azurerm_cdn_frontdoor_profile](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_profile)

Also, there are two separate CLI commands to list the resources.
- azurerm_frontdoor: `az network front-door list`
- azurerm_cdn_frontdoor_profile: `az afd profile list`

Thanks!

**Comment by ParthaI** [comment]
Hey @Priyanka-Chatterjee-2000, I have added support for the new table `azure_cdn_frontdoor_profile` in [this PR](https://github.com/turbot/steampipe-plugin-azure/pull/777).

Please give it a shot and let me know if it fulfils the requirements or if you need to ass any other properties to this table.

Thanks!
