### ISSUE TITLE
Fix column `autoscale_settings_max_throughput` in table azure_cosmosdb_sql_database

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#772]
**Describe the bug**
The column autoscale_settings_max_throughput in the table azure_cosmosdb_sql_database is coming up as null even though we have data.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by ParthaI** [comment]
Hi @khushboo9024, As per my findings the APIs(List/Get) have a property named `MaxThroughput` under [SQLDatabaseGetProperties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/cosmos-db/mgmt/2022-08-15/documentdb#SQLDatabaseGetProperties). However, the API is returning null value for this property all the time.
- Also, the azure CLI command(`az cosmosdb sql database list --resource-group test7 --account-name test4446666`/` az cosmosdb sql database show --resource-group test7 --account-name test4446666 --name test5353`) is also not returning any result for autoscaling settings.
- As per my understanding, we can set the autoscaling settings on the container level.
- It would be better if we add support for the table `azure_cosmosdb_sql_container`

Thanks!

**Comment by ParthaI** [comment]
@khushboo9024, I have pushed a rough code into the `issue-772` branch that adds a new table called `azure_cosmosdb_sql_container`. With this, I am able to retrieve the throughput details for the containers.

```sql
> select name,account_name, database_name, jsonb_pretty(throughput_settings)  from azure_cosmosdb_sql_container
+--------+--------------+---------------+---------------------------+
| name   | account_name | database_name | jsonb_pretty              |
+--------+--------------+---------------+---------------------------+
| test53 | test93       | test63        | <null>                    |
| Items  | tes-acc33    | ToDoList      | {                         |
|        |              |               |     "Resource": {         |
|        |              |               |         "throughput": 400 |
|        |              |               |     }                     |
|        |              |               | }                         |
+--------+--------------+---------------+---------------------------+

Time: 5.4s. Rows returned: 2. Rows fetched: 2. Hydrate calls: 2.


```

Please give it a go in the PR branch and let me know if that helps. I will do some cleanup in the branch and raise the PR then.

Thanks!

**Comment by ParthaI** [comment]
@khushboo9024, As we haven't received a response from you in a while, we're assuming that the issue has either been resolved or is no longer a concern.

Therefore, we will go ahead and close this issue. If you still need assistance or have any other questions, please feel free to reach out. We'd be glad to reopen the issue and provide further support.

Thank you!
