### ISSUE TITLE
Add `resource_attached` column in table `azure_network_interface`

### ISSUE THREAD

**Issue by marcbrlcln** [turbot/steampipe-plugin-azure#778]
**Is your feature request related to a problem? Please describe.**
I can't see which resource is attached to a network interface.

**Describe the solution you'd like**
Have a column with the name of the resource attached to the network interface.

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
Hello, @marcbrlcln, As per my knowledge, there is no direct Azure CLI command/ API that lists all attached resources to a Network Interface (NIC) in one go. However, we can aggregate the columns(`network_security_group_id`, `virtual_machine_id`, `dscp_configuration`, `private_link_service`, `private_endpoint`, etc...) to distinguish the attached resources.

BTW, I noticed a few missing columns in the table that are present in the [API response](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/network/mgmt/2022-07-01/network#InterfacePropertiesFormat).

I have raised a [draft PR](https://github.com/turbot/steampipe-plugin-azure/pull/779) to address the missing columns. Please take a look at the PR and let us know if this helps.

We would also love to hear your thoughts if you have any.

Thanks!

**Comment by marcbrlcln** [comment]
Hi, yes it's what I needed. Thank you !

**Comment by ParthaI** [comment]
Thanks @marcbrlcln, for your confirmation. Did you get a chance to try it in the PR branch?

**Comment by marcbrlcln** [comment]
I have tried my query on the PR branch and yes it's working fine. 
It's missing a column for the resource [Azure NetApp File](https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction) volume, because some Network interfaces are attached to a volume. But I don't see this resource in the API response.

**Comment by marcbrlcln** [comment]
I found this :
[https://github.com/Azure/azure-sdk-for-go/tree/v68.0.0/services/netapp/mgmt](url)
But I don't know if it's helpful.

**Comment by ParthaI** [comment]
Hi @marcbrlcln, I was having a look at the [Network Interface Properties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/network/mgmt/2022-07-01/network#InterfacePropertiesFormat) return by the API.

I did not find any properties related to [Azure NetApp Files](https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction).

Additionally, there is no such API for network interfaces that returns details about attached Azure NetApp Files.

I'm not sure how helpful it would be to have a separate table for volumes, but it might be beneficial. Here are [the properties](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/netapp/mgmt/2021-10-01/netapp/models.go#L5110) for the volume we will get.

Alternatively, could we consider joining the `azure_compute_*` tables to retrieve the necessary details?

Thanks!

**Comment by marcbrlcln** [comment]
Hi, I've succeded to do what I wanted with column `hosted_workloads`. Thanks for the other columns.
