### ISSUE TITLE
Table from Azure returns invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by halit-c4c** [turbot/steampipe-plugin-azure#791]
**Describe the bug**
I'm using turbot pipes and trying to run a query. But I got an error:

"azure_compute_virtual_machine" table returns error:
ERROR: rpc error: code = Unknown desc = c4ctest_azure: failed to populate column 'power_state': rpc error: code = Internal desc = transform getPowerState failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
query:
`select
  *
from
  azure_compute_virtual_machine
limit
  100;`

**Steampipe version (`steampipe -v`)**
I'm using turbot pipes

**Plugin version (`steampipe plugin list`)**
I'm using turbot pipes

**To reproduce**
Execute the querie added in the description

**Expected behavior**
Should not receive the error "invalid memory address or nil pointer dereference" and return results

**Additional context**

**Comment by ParthaI** [comment]
Hello @halit-c4c,

I apologize for the inconvenience.

I investigated the issue but was unable to replicate the error in my local environment. All the time I am getting the result without any error.

Here are the results for the VM named `test-power`:

1. **Creating state**

```
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| tets-delete     | deallocated |
| test-power      |             |
| turbottest95054 | running     |
+-----------------+-------------+
```

2. **Starting state**

```
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| turbottest95054 | running     |
| test-power      | starting    |
| tets-delete     | deallocated |
+-----------------+-------------+
```

3. **Running state**

```sql
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| turbottest95054 | running     |
| test-power      | running     |
| tets-delete     | deallocated |
+-----------------+-------------+
```

4. **Stopping state**

```
> select name, power_state from azure_compute_virtual_machine
+-----------------+--------------+
| name            | power_state  |
+-----------------+--------------+
| turbottest95054 | running      |
| test-power      | running      |
| tets-delete     | deallocating |
+-----------------+--------------+
```

5. **Stopped state**

```sql
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| turbottest95054 | running     |
| test-power      | deallocated |
| tets-delete     | deallocated |
+-----------------+-------------+
```

6. **Terminating state**

```sql
> select name, power_state from azure_compute_virtual_machine
+-----------------+-------------+
| name            | power_state |
+-----------------+-------------+
| tets-delete     | deallocated |
| test-power      |             |
| turbottest95054 | running     |
+-----------------+-------------+
```

Could you please provide more context about the steps you took to reproduce the error?
Also, could you please confirm if you are able to replicate the same in your local environment?

Thank you!

**Comment by ParthaI** [comment]
Hi @halit-c4c, have you had a chance to review the above conversation?

**Comment by ParthaI** [comment]
Hi @halit-c4c, FYI, I have raised a [PR](https://github.com/turbot/steampipe-plugin-azure/pull/804) to address the issue mentioned above. The fixes in this PR should resolve the problem.

Thank you!
