### ISSUE TITLE
Ensure that the latest OS Patches for all Virtual Machines are applied

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-azure#81]
**Is your feature request related to a problem? Please describe.**
This is to achieve some of the CIS steps 7.5

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Please note that at this point of time, there is no API/CLI mechanism available to
programmatically conduct security assessment for this recommendation.

**Comment by rajlearner17** [comment]
As mentioned, this remains a manual process.
