### ISSUE TITLE
azure_mysql_flexible_server query always returns public_network_access as "enabled" even if db does not have public access.

### ISSUE THREAD

**Issue by ManojDhanorkar** [turbot/steampipe-plugin-azure#819]
Below azure_mysql_flexible_server query always returns public_network_access as "enabled" even if db does not have public access.

select
  name,
  id,
  public_network_access
from
  azure_mysql_flexible_server

Steampipe v0.22.1

Azure  0.64.0

**Comment by ParthaI** [comment]
Hi @ManojDhanorkar, Sorry to see that you are encountering the error.

- In our project we use the [ListByResourceGroup](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/mysql/mgmt/2021-05-01/mysqlflexibleservers#ServersClient.ListByResourceGroup) API call from the [mysqlflexibleservers](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/profiles/latest/mysql/mgmt/mysqlflexibleservers#ServersClient) package.
- This API returns an attribute called `PublicNetworkAccess` under the [Network](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/mysql/mgmt/2021-05-01/mysqlflexibleservers#Network) property.
- However, the PublicNetworkAccess value we receive is always `Enabled`, regardless of whether it is actually enabled or disabled in the portal.

I have raised an issue on the Azure Go SDK repository to address this response. You can track the [issue here](https://github.com/Azure/azure-sdk-for-go/issues/23320).

We will revisit this matter once it is resolved on the Azure Go SDK side.

Thanks!

**Comment by ManojDhanorkar** [comment]
I suspect this problem may be there in mysql standalone , postgres standalone and postgres flexible. Will this new PR fix it across all of them ?

**Comment by ManojDhanorkar** [comment]
when this would get merged ?

**Comment by ManojDhanorkar** [comment]
which query should be used on azure_postgresql_flexible_server  to know if server has public access enabled. I searched a lot but could not find one.

**Comment by ManojDhanorkar** [comment]
for azure_postgresql_flexible_server   ( psotgress ) should I raise new issue ? I am looking for similar column in postgres. Any pointers around that.

**Comment by ManojDhanorkar** [comment]
On the mysql PR some checks are failing . https://github.com/turbot/steampipe-plugin-azure/pull/820

**Comment by ParthaI** [comment]
> for azure_postgresql_flexible_server ( postgress ) should I raise new issue ? I am looking for similar column in postgres. Any pointers around that.

Yes, please raise a separate issue.

> On the mysql PR some checks are failing . https://github.com/turbot/steampipe-plugin-azure/pull/820

It is not due to the code changes in that PR. It is due to the use of a few deprecated Azure Go packages. We will be working on it.

**Comment by ManojDhanorkar** [comment]
thanks

**Comment by ManojDhanorkar** [comment]
When is the next release planned where we can expect the changes to be included ?

**Comment by ManojDhanorkar** [comment]
will this be available in https://github.com/turbot/steampipe-plugin-azure/releases/tag/v0.65.0 ?
