### ISSUE TITLE
`web_application_firewall_configuration` in `azure_application_gateway`  table always return NULL when the Application gateway is not associated with an Application Gateway WAF policy.

### ISSUE THREAD

**Issue by marcbrlcln** [turbot/steampipe-plugin-azure#825]
**Describe the bug**
`web_application_firewall_configuration` in `azure_application_gateway`  table always return NULL when the Application gateway is not associated with an Application Gateway WAF policy.

**Steampipe version**
Steampipe v0.23.3

**Plugin version**
azure 0.64.0

**To reproduce**
Here is an Application gateway with an associated WAF policy : 
![Capture d'écran 2024-08-20 120403](https://github.com/user-attachments/assets/74c09b96-5ab1-4d36-bdf0-6e5113a32120)
I query the `web_application_firewall_configuration` details using Steampipe : 

```
> SELECT name, jsonb_pretty(web_application_firewall_configuration) FROM azure_application_gateway
+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name                        | jsonb_pretty                                                                                                                                                                                       |
+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| agw-demo-tech-prod-frc-01   | {                                                                                                                                                                                                  |
|                             |     "CustomRules": [],                                                                                                                                                                             |
|                             |     "ManagedRules": {                                                                                                                                                                              |
|                             |         "exclusions": [                                                                                                                                                                            |
|                             |         ],                                                                                                                                                                                         |
|                             |         "managedRuleSets": [                                                                                                                                                                       |
|                             |             { ...                                                                                                                                                                                  |
+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

It works fine for this App gateway, but with an App gateway with no associated WAF policy like this one :

![Capture d'écran 2024-08-20 143259](https://github.com/user-attachments/assets/664d9ae0-0c8b-4e95-9c63-d20412e02bcc)

We can see the configurations in Azure CLI : 
```
az network application-gateway waf-policy list
[
  {
    "customRules": [],
    "etag": "W/\"3e.................................\"",
    "httpListeners": [
      {
        "id": "/subscriptions/c8................................./resourceGroups/rg-demo-prod/providers/Microsoft.Network/applicationGateways/agw-demo-prod-frc-waf/httpListeners/demo-frc-prod-listener-https-sgh2re",
        "resourceGroup": "rg-demo-prod"
      },
      {
        "id": "/subscriptions/c8................................./resourceGroups/rg-demo-prod/providers/Microsoft.Network/applicationGateways/agw-demo-prod-frc-waf/httpListeners/demo-frc-prod-listener-http-sgh2re",
        "resourceGroup": "rg-demo-prod"
      }
    ],
    "id": "/subscriptions/c8................................./resourceGroups/rg-demo-prod/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/wafwdemofrcprod",
    "location": "francecentral",
    "managedRules": {
      "exclusions": [],
      "managedRuleSets": [
        {
          "ruleGroupOverrides": [],
          "ruleSetType": "OWASP",
          "ruleSetVersion": "3.2"
        }
      ]
    },
    "name": "wafwdemofrcprod",
    "policySettings": {
      "fileUploadEnforcement": true,
      "fileUploadLimitInMb": 100,
      "maxRequestBodySizeInKb": 128,
      "mode": "Prevention",
      "requestBodyCheck": true,
      "requestBodyEnforcement": true,
      "requestBodyInspectLimitInKB": 128,
      "state": "Enabled"
    },
    "provisioningState": "Succeeded",
    "resourceGroup": "rg-demo-prod",
    "tags": {},
    "type": "Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies"
  },
  {
    ...
  }
]
```
The query always return NULL for this type of configurations : 
```
> SELECT name, jsonb_pretty(web_application_firewall_configuration) FROM azure_application_gateway
+--------------------------+--------------+
| name                     | jsonb_pretty |
+--------------------------+--------------+
| agw-demo-preprod-frc-waf | <null>       |
| agw-demo-prod-frc-waf    | <null>       |
+--------------------------+--------------+
```
**Expected behavior**
The `web_application_firewall_configuration` column should return the configurations of WAFs in either cases.

**Additional context**
The get API response return the same results as the CLI so the issue may be related to how the Steampipe Azure plugin retrieves and displays WAF policy details.

**Comment by ParthaI** [comment]
Hello @marcbrlcln,

I apologize for any inconvenience.

I reviewed the `azure_application_gateway` table, and here’s what I found:

- It seems that the behavior you're experiencing is expected.
- The `azure_application_gateway` table provides information about Azure Application Gateways.
- If a gateway doesn't have an associated firewall policy, the `firewall_policy` and `web_application_firewall_configuration` columns will not be populated.
- This is consistent with the behavior of the Azure Application Gateway CLI command (`az network application-gateway list`), which returns similar results.

For example:

```bash
az network application-gateway list | jq '.[] | {name, firewallPolicy}'
{
  "name": "test-gw13",
  "firewallPolicy": {
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/new-rg/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/test4355",
    "resourceGroup": "new-rg"
  }
}
{
  "name": "test-no-asso",
  "firewallPolicy": null
}
```

As I understand it, the command `az network application-gateway waf-policy list` returns all firewall policies available in your subscription. If you'd like, we can consider adding this information as a separate table.

If you need a table that specifically returns all firewall policies in your subscription, please feel free to raise a new issue for that request.

Thanks!

**Comment by marcbrlcln** [comment]
Hello,

Yes it can be useful to have this table only for waf policies, I'll raise a new issue.

Nevertheless, it'll not help me in my query because the name of the app gateway associated with the WAF policy will not be mentionned as the WAF configurations is builtin in the app gateway.

With this CLI command we can see the WAF configurations of the app gateway when there is no associated WAF policy.
```
az network application-gateway list --query '[].{name: name, webApplicationFirewallConfiguration: webApplicationFirewallConfiguration, sku: sku, firewallPolicy: firewallPolicy}'
[
  {
    "firewallPolicy": null,
    "name": "app-demo-euw-prod-appgw",
    "sku": {
      "family": "Generation_1",
      "name": "WAF_v2",
      "tier": "WAF_v2"
    },
    "webApplicationFirewallConfiguration": {
      "disabledRuleGroups": [],
      "enabled": false,
      "fileUploadLimitInMb": 100,
      "firewallMode": "Detection",
      "maxRequestBodySizeInKb": 128,
      "requestBodyCheck": true,
      "ruleSetType": "OWASP",
      "ruleSetVersion": "3.1"
    }
  },
  {
    "firewallPolicy": null,
    "name": "app2-demo-euw-prod-appgw",
    "sku": {
      "family": "Generation_1",
      "name": "WAF_v2",
      "tier": "WAF_v2"
    },
    "webApplicationFirewallConfiguration": {
      "disabledRuleGroups": [],
      "enabled": false,
      "fileUploadLimitInMb": 100,
      "firewallMode": "Detection",
      "maxRequestBodySizeInKb": 128,
      "requestBodyCheck": true,
      "ruleSetType": "OWASP",
      "ruleSetVersion": "3.1"
    }
  }
]
```

It would be useful for my query to have the webApplicationFirewallConfiguration information in the `azure_application_gateway` table specifically the "enabled" field which is needed for query development .

**Comment by ParthaI** [comment]
Hi @marcbrlcln,

I've been looking into the issue further, and here are my findings. Please take a look:

- I ran the Azure CLI command: 
  ```bash
  az network application-gateway list --query '[].{name: name, webApplicationFirewallConfiguration: webApplicationFirewallConfiguration, sku: sku, firewallPolicy: firewallPolicy}'
  ```
  However, the `webApplicationFirewallConfiguration` is always returning as null.
  
- I also tried using the [Azure API explorer](https://learn.microsoft.com/en-us/rest/api/application-gateway/application-gateways/list?view=rest-application-gateway-2024-01-01&tabs=HTTP#code-try-0), but it similarly does not return the `webApplicationFirewallConfiguration` value.

Here's an example of the output:

```json
[
  {
    "firewallPolicy": {
      "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/new-rg/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/test53",
      "resourceGroup": "new-rg"
    },
    "name": "test5333",
    "sku": {
      "name": "WAF_v2",
      "tier": "WAF_v2"
    },
    "webApplicationFirewallConfiguration": null
  }
]
```

- I noticed that your Application Gateway tier is `WAF_v2`, which requires a firewall policy to be attached.
- It’s not possible to create an Application Gateway with the `WAF_v2` tier without associating a firewall policy.

Could you please help me understand if I might be missing something or if there's another way to replicate the same behavior you're experiencing? 

Thank you!

**Comment by ParthaI** [comment]
Ah, my mistake—after 1-2 hours following the creation of the Application Gateway, the `webApplicationFirewallConfiguration` value gets populated. I'm looking into it further.

**Comment by marcbrlcln** [comment]
Hi @ParthaI, thank you for your work on this issue.
