### ISSUE TITLE
Ensure that the endpoint protection for all Virtual Machines is installed

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-azure#84]
**Is your feature request related to a problem? Please describe.**
This is to achieve some of the CIS steps 7.6

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
At this point in time, there is no API mechanism available.

**Comment by rajlearner17** [comment]
Marking this closed to pursue it when the user's requirement & API support are available.
