### ISSUE TITLE
Error: no connection config loaded for connection 'azure' (SQLSTATE HV000) on Azure VM query

### ISSUE THREAD

**Issue by ManojDhanorkar** [turbot/steampipe-plugin-azure#846]
We see below error intermittently on the VM query. 

```
Error: no connection config loaded for connection 'azure' (SQLSTATE HV000)

```
select
  _ctx ->> 'connection_name' as subscription_info,
  subscription_id,
  region,
  name,
  computer_name,
  power_state,
  private_ips,
  public_ips,
  vm_id,
  size,
  os_type,
  image_offer,
  image_sku,
  os_disk_name,
  tags
from
  azure_compute_virtual_machine
order by 
  subscription_info

**Comment by ParthaI** [comment]
Hello @ManojDhanorkar, apologies for the inconvenience. Could you please share how your Steampipe connection config file (`~/.steampipe/config/azure.spc`) looks (with any sensitive information removed, of course)?

When querying a table like `azure_compute_virtual_machine`, Steampipe will, by default, use the default connection for the plugin. Do you have a connection named `azure` in your configuration?

If not, could you try running the queries by specifying the connection name before the table, like this: `<connection name>.azure_compute_virtual_machine`?

**Comment by ManojDhanorkar** [comment]
Thanks for this .. We will try it.

**Comment by ParthaI** [comment]
Hi @ManojDhanorkar, have you had a chance to give it a shot again based on our previous conversation?

**Comment by ManojDhanorkar** [comment]
Yes. this is working now after using azure connection. Thanks a lot.
