### ISSUE TITLE
Add columns in table "azure_storage_account" to store logging requests for 'Table properties`

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-azure#92]
**Is your feature request related to a problem? Please describe.**
Currently we don't have any column to store logging requests `Read`, `Write` and `Delete` of Table properties.

**Describe the solution you'd like**
Add new columns to store above properties.

**Additional context**
![image](https://user-images.githubusercontent.com/43408569/114411956-4cda3500-9bca-11eb-85bc-115d786627b1.png)

**Comment by visiit** [comment]
don't find any API related to this.

**Comment by rajlearner17** [comment]
Marking this closed to pursue it when the user's requirement & API support are available.
